### ISSUE TITLE
create better layout

### ISSUE THREAD

**Issue by danieldotlewis** [danieldotlewis/probable-adventure#12]
make the layout and css prettier

**Comment by DalisaNguyen** [comment]
Hello, may I work on this?

**Comment by danieldotlewis** [comment]
yes please work on this

**Comment by danieldotlewis** [comment]
we're using this stylesheet
https://utahhealthcare.github.io/gloss-docs/elements/

**Comment by DalisaNguyen** [comment]
Awesome, thank you! Any preferences on the color, layout, etc?

**Comment by danieldotlewis** [comment]
we're now copying the example layout located here
https://utahhealthcare.github.io/gloss-docs/example-layouts/clinical/clinical-form/

https://github.com/danieldotlewis/probable-adventure/issues/14

**Comment by DalisaNguyen** [comment]
Okay, would I be assigned to this instead?
