### ISSUE TITLE
rebrand gloss-docs/example-layouts/clinical/clinical-form

### ISSUE THREAD

**Issue by danieldotlewis** [danieldotlewis/probable-adventure#14]
we're now copying the example layout located here
https://utahhealthcare.github.io/gloss-docs/example-layouts/clinical/clinical-form/

rebranding for UMB IT

**Comment by DalisaNguyen** [comment]
Okay, would I be able to work on this instead?

**Comment by danieldotlewis** [comment]
rebrand MVP established
